create table if not exists todo_list (
    id bigint generated by default as identity primary key,
    name varchar(255),
    owner_email varchar(255),
    created_at timestamp(6)
);

create table if not exists todo_view (
    id bigint generated by default as identity primary key,
    name varchar(255),
    search varchar(255),
    category varchar(255),
    tag varchar(255),
    priority varchar(255),
    completed boolean,
    archived boolean,
    sort_by varchar(255),
    direction varchar(255),
    page_size integer,
    created_at timestamp(6)
);

create table if not exists todo_history (
    id bigint generated by default as identity primary key,
    action varchar(255),
    todo_id bigint,
    before_state text,
    after_state text,
    undone boolean,
    created_at timestamp(6),
    undone_at timestamp(6)
);

create table if not exists todo (
    id bigint generated by default as identity primary key,
    title varchar(255),
    description varchar(255),
    email varchar(255),
    due_time timestamp(6),
    reminder_time timestamp(6),
    reminder_minutes_before integer,
    list_id bigint,
    category varchar(255),
    recurrence_pattern varchar(255),
    recurrence_interval integer,
    priority varchar(255),
    display_order bigint,
    completed boolean not null default false,
    created_at timestamp(6),
    tracked_seconds bigint,
    timer_started_at timestamp(6),
    timer_running boolean,
    archived boolean,
    reminder_sent boolean,
    overdue_notification_sent boolean,
    token varchar(255),
    constraint fk_todo_list foreign key (list_id) references todo_list(id)
);

create table if not exists todo_dependencies (
    todo_id bigint not null,
    dependency_id bigint not null,
    primary key (todo_id, dependency_id),
    constraint fk_todo_dependencies_todo foreign key (todo_id) references todo(id) on delete cascade,
    constraint fk_todo_dependencies_dependency foreign key (dependency_id) references todo(id) on delete cascade
);

create table if not exists todo_tags (
    todo_id bigint not null,
    tag varchar(255),
    constraint fk_todo_tags_todo foreign key (todo_id) references todo(id) on delete cascade
);

create table if not exists todo_list_shared_emails (
    todo_list_id bigint not null,
    email varchar(255),
    constraint fk_todo_list_shared_emails_list foreign key (todo_list_id) references todo_list(id) on delete cascade
);

create index if not exists idx_todo_list_id on todo(list_id);
create index if not exists idx_todo_created_at on todo(created_at);
create index if not exists idx_todo_due_time on todo(due_time);
create index if not exists idx_todo_reminder_time on todo(reminder_time);
create index if not exists idx_todo_completed_archived on todo(completed, archived);
create index if not exists idx_todo_history_todo_id on todo_history(todo_id);
