create table if not exists users (
    id bigint generated by default as identity primary key,
    email varchar(255) unique not null,
    password varchar(255) not null,
    name varchar(255) not null,
    role varchar(20) not null default 'USER',
    created_at timestamp(6),
    updated_at timestamp(6)
);

create index if not exists idx_users_email on users(email);
